stages:
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

.default-cache: &default-cache
  before_script:
    - npm ci --cache .npm --prefer-offline

build:
  extends:
    - .default-cache
  image: node:14.17.0-alpine
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./build/

deploy:
  image: ubuntu:latest
  stage: deploy
  script:
    - apt -qq update && apt upgrade -qqy openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - rsync -a --progress --human-readable
      --exclude-from '.gitignore'
      --exclude ./.gitignore
      --exclude ./.npm
      --exclude ./.git
      ./build/* deploy@139.177.176.70:~/realworld/public/
